"""
Production PDF report generator using ReportLab.
Generates institutional-grade portfolio analysis reports.
"""
import io
import logging
import warnings
from datetime import datetime
from typing import Dict, List, Optional

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import numpy as np

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm, mm
from reportlab.platypus import (
    BaseDocTemplate, Frame, PageTemplate,
    Paragraph, Spacer, Table, TableStyle,
    Image, HRFlowable, PageBreak, KeepTogether,
)
from reportlab.platypus.flowables import HRFlowable
from reportlab.pdfgen import canvas as rl_canvas

warnings.filterwarnings("ignore")
logger = logging.getLogger(__name__)

# ── Brand colors ──────────────────────────────────────────────
C_BG        = colors.HexColor('#0d1117')
C_CARD      = colors.HexColor('#161b22')
C_BLUE      = colors.HexColor('#3b82f6')
C_GREEN     = colors.HexColor('#22c55e')
C_RED       = colors.HexColor('#ef4444')
C_YELLOW    = colors.HexColor('#f59e0b')
C_GRAY      = colors.HexColor('#6b7280')
C_LIGHTGRAY = colors.HexColor('#9ca3af')
C_WHITE     = colors.white
C_DARK_TEXT = colors.HexColor('#1f2937')

PAGE_W, PAGE_H = A4


def _styles() -> dict:
    base = getSampleStyleSheet()
    return {
        "title": ParagraphStyle(
            "Title", fontSize=24, textColor=C_WHITE,
            fontName="Helvetica-Bold", spaceAfter=4,
            alignment=TA_LEFT,
        ),
        "subtitle": ParagraphStyle(
            "Subtitle", fontSize=11, textColor=C_LIGHTGRAY,
            fontName="Helvetica", spaceAfter=2,
        ),
        "section": ParagraphStyle(
            "Section", fontSize=13, textColor=C_WHITE,
            fontName="Helvetica-Bold", spaceBefore=12, spaceAfter=6,
        ),
        "body": ParagraphStyle(
            "Body", fontSize=9, textColor=C_LIGHTGRAY,
            fontName="Helvetica", spaceAfter=4, leading=14,
        ),
        "small": ParagraphStyle(
            "Small", fontSize=7.5, textColor=C_GRAY,
            fontName="Helvetica", spaceAfter=2,
        ),
        "metric_label": ParagraphStyle(
            "MetricLabel", fontSize=7.5, textColor=C_GRAY,
            fontName="Helvetica", alignment=TA_LEFT,
        ),
        "metric_value": ParagraphStyle(
            "MetricValue", fontSize=13, textColor=C_WHITE,
            fontName="Helvetica-Bold", alignment=TA_LEFT,
        ),
        "table_header": ParagraphStyle(
            "TH", fontSize=7.5, textColor=C_GRAY,
            fontName="Helvetica-Bold", alignment=TA_LEFT,
        ),
        "table_cell": ParagraphStyle(
            "TC", fontSize=8.5, textColor=C_LIGHTGRAY,
            fontName="Helvetica", alignment=TA_LEFT,
        ),
        "positive": ParagraphStyle(
            "Pos", fontSize=8.5, textColor=C_GREEN,
            fontName="Helvetica-Bold", alignment=TA_RIGHT,
        ),
        "negative": ParagraphStyle(
            "Neg", fontSize=8.5, textColor=C_RED,
            fontName="Helvetica-Bold", alignment=TA_RIGHT,
        ),
        "highlight": ParagraphStyle(
            "HL", fontSize=8.5, textColor=C_BLUE,
            fontName="Helvetica-Bold", alignment=TA_LEFT,
        ),
    }


def _on_page(canvas, doc):
    """Draw dark background, header and footer on every page."""
    canvas.saveState()

    # Dark background
    canvas.setFillColor(C_BG)
    canvas.rect(0, 0, PAGE_W, PAGE_H, fill=True, stroke=False)

    # Top bar
    canvas.setFillColor(C_BLUE)
    canvas.rect(0, PAGE_H - 8*mm, PAGE_W, 8*mm, fill=True, stroke=False)

    # Logo text
    canvas.setFillColor(C_WHITE)
    canvas.setFont("Helvetica-Bold", 10)
    canvas.drawString(20*mm, PAGE_H - 5.5*mm, "PortfolioAI")

    # Report title in header
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(colors.HexColor('#93c5fd'))
    canvas.drawRightString(PAGE_W - 20*mm, PAGE_H - 5.5*mm, "Portfolio Analysis Report")

    # Footer
    canvas.setFillColor(colors.HexColor('#1e2937'))
    canvas.rect(0, 0, PAGE_W, 10*mm, fill=True, stroke=False)

    canvas.setFont("Helvetica", 7)
    canvas.setFillColor(C_GRAY)
    canvas.drawString(20*mm, 3.5*mm,
        "Generated by PortfolioAI · For informational purposes only · Not financial advice")
    canvas.drawRightString(PAGE_W - 20*mm, 3.5*mm,
        f"Page {doc.page} · {datetime.now().strftime('%d %b %Y')}")

    # Thin separator line above footer
    canvas.setStrokeColor(colors.HexColor('#374151'))
    canvas.setLineWidth(0.5)
    canvas.line(20*mm, 10*mm, PAGE_W - 20*mm, 10*mm)

    canvas.restoreState()


def _metric_table(metrics: List[tuple], cols: int = 4) -> Table:
    """
    Build a card-style metric table.
    metrics = [(label, value, color), ...]
    """
    s = _styles()
    rows = []
    row  = []
    for i, (label, value, color) in enumerate(metrics):
        cell_color = colors.HexColor(color) if isinstance(color, str) else color
        cell = [
            Paragraph(label, s["metric_label"]),
            Paragraph(str(value), ParagraphStyle(
                "mv", fontSize=13, textColor=cell_color,
                fontName="Helvetica-Bold",
            )),
        ]
        row.append(cell)
        if len(row) == cols:
            rows.append(row)
            row = []
    if row:
        while len(row) < cols:
            row.append([Paragraph("", s["metric_label"]), Paragraph("", s["metric_value"])])
        rows.append(row)

    col_w = (PAGE_W - 40*mm) / cols

    t = Table(rows, colWidths=[col_w] * cols, rowHeights=None)
    t.setStyle(TableStyle([
        ('BACKGROUND',   (0,0), (-1,-1), C_CARD),
        ('ROUNDEDCORNERS', [6]),
        ('TOPPADDING',   (0,0), (-1,-1), 8),
        ('BOTTOMPADDING',(0,0), (-1,-1), 8),
        ('LEFTPADDING',  (0,0), (-1,-1), 10),
        ('RIGHTPADDING', (0,0), (-1,-1), 10),
        ('LINEAFTER',    (0,0), (-2,-1), 0.5, colors.HexColor('#1f2937')),
        ('LINEBELOW',    (0,0), (-1,-2), 0.5, colors.HexColor('#1f2937')),
        ('VALIGN',       (0,0), (-1,-1), 'TOP'),
    ]))
    return t


def _holdings_table(holdings: List[Dict]) -> Table:
    s       = _styles()
    headers = ['Symbol','Sector','Qty','Avg Price','Curr Price','Invested','P&L','Return']
    rows    = [[Paragraph(h, s["table_header"]) for h in headers]]

    for h in holdings[:30]:
        pnl     = h.get('pnl') or 0
        pnl_pct = h.get('pnl_pct') or 0
        prefix  = '₹' if h.get('currency','INR') == 'INR' else '$'
        style   = s["positive"] if pnl >= 0 else s["negative"]
        loc     = 'en-IN'

        rows.append([
            Paragraph(h.get('symbol',''), s["highlight"]),
            Paragraph(h.get('sector') or '—', s["table_cell"]),
            Paragraph(str(int(h.get('quantity',0))), s["table_cell"]),
            Paragraph(f"{prefix}{h.get('avg_buy_price',0):,.0f}", s["table_cell"]),
            Paragraph(
                f"{prefix}{h.get('current_price',0):,.0f}" if h.get('current_price') else '—',
                s["table_cell"]
            ),
            Paragraph(f"{prefix}{h.get('invested_value',0):,.0f}", s["table_cell"]),
            Paragraph(
                f"{'+' if pnl>=0 else ''}{prefix}{pnl:,.0f}",
                s["positive"] if pnl >= 0 else s["negative"]
            ),
            Paragraph(
                f"{'+' if pnl_pct>=0 else ''}{pnl_pct:.1f}%" if pnl_pct else '—',
                s["positive"] if pnl_pct >= 0 else s["negative"]
            ),
        ])

    col_widths = [2.8*cm, 2.4*cm, 1.2*cm, 1.9*cm, 1.9*cm, 2.0*cm, 2.0*cm, 1.8*cm]
    t = Table(rows, colWidths=col_widths, repeatRows=1)
    t.setStyle(TableStyle([
        ('BACKGROUND',    (0,0), (-1,0),  colors.HexColor('#1e2937')),
        ('BACKGROUND',    (0,1), (-1,-1), C_CARD),
        ('ROWBACKGROUNDS',(0,1), (-1,-1), [C_CARD, colors.HexColor('#0f1923')]),
        ('TEXTCOLOR',     (0,0), (-1,0),  C_GRAY),
        ('FONTNAME',      (0,0), (-1,0),  'Helvetica-Bold'),
        ('FONTSIZE',       (0,0), (-1,0), 7.5),
        ('TOPPADDING',    (0,0), (-1,-1), 5),
        ('BOTTOMPADDING', (0,0), (-1,-1), 5),
        ('LEFTPADDING',   (0,0), (-1,-1), 6),
        ('RIGHTPADDING',  (0,0), (-1,-1), 6),
        ('LINEBELOW',     (0,0), (-1,-1), 0.3, colors.HexColor('#1f2937')),
        ('VALIGN',        (0,0), (-1,-1), 'MIDDLE'),
    ]))
    return t


def _pie_chart(sector_breakdown: List[Dict]) -> Optional[io.BytesIO]:
    """Generate sector allocation pie chart."""
    if not sector_breakdown:
        return None
    try:
        fig, ax = plt.subplots(1, 1, figsize=(5, 4))
        fig.patch.set_facecolor('#161b22')
        ax.set_facecolor('#161b22')

        labels = [s['sector'] for s in sector_breakdown[:8]]
        sizes  = [s['weight_pct'] for s in sector_breakdown[:8]]
        palette = [
            '#3b82f6','#22c55e','#f59e0b','#ef4444','#8b5cf6',
            '#06b6d4','#f97316','#ec4899','#10b981','#6366f1'
        ]
        wedge_colors = palette[:len(labels)]

        wedges, texts, autotexts = ax.pie(
            sizes, labels=None, colors=wedge_colors,
            autopct='%1.1f%%', startangle=90,
            pctdistance=0.75,
            wedgeprops={'linewidth': 1.5, 'edgecolor': '#0d1117'},
        )
        for at in autotexts:
            at.set_color('white')
            at.set_fontsize(7)

        legend = ax.legend(
            wedges, labels, loc='center left',
            bbox_to_anchor=(1, 0.5), fontsize=7,
            labelcolor='#9ca3af',
            facecolor='#1e2937',
            edgecolor='#374151',
            framealpha=0.8,
        )

        ax.set_title('Sector Allocation', color='white', fontsize=10, pad=10)
        plt.tight_layout()

        buf = io.BytesIO()
        plt.savefig(buf, format='png', dpi=120, bbox_inches='tight',
                    facecolor='#161b22', transparent=False)
        plt.close(fig)
        buf.seek(0)
        return buf
    except Exception as e:
        logger.warning(f"Pie chart failed: {e}")
        return None


def _pnl_bar_chart(holdings: List[Dict]) -> Optional[io.BytesIO]:
    """Top gainers/losers bar chart."""
    valid = [h for h in holdings if h.get('pnl') is not None]
    if len(valid) < 2:
        return None
    try:
        valid.sort(key=lambda x: x.get('pnl', 0))
        bottom_5 = valid[:5]
        top_5    = list(reversed(valid[-5:]))
        combined = bottom_5 + top_5

        fig, ax = plt.subplots(figsize=(10, 4))
        fig.patch.set_facecolor('#161b22')
        ax.set_facecolor('#0d1117')

        symbols = [h['symbol'].replace('.NS','').replace('.BO','') for h in combined]
        pnls    = [h.get('pnl',0) for h in combined]
        bar_colors = ['#ef4444' if p < 0 else '#22c55e' for p in pnls]

        bars = ax.barh(symbols, pnls, color=bar_colors, edgecolor='none', height=0.6)

        for bar, val in zip(bars, pnls):
            x   = bar.get_width()
            txt = f"₹{abs(val):,.0f}"
            ax.text(
                x + (max(pnls) * 0.01 if x >= 0 else min(pnls) * 0.01),
                bar.get_y() + bar.get_height()/2,
                txt, va='center',
                ha='left' if x >= 0 else 'right',
                fontsize=7, color='#9ca3af'
            )

        ax.axvline(x=0, color='#374151', linewidth=0.8)
        ax.set_xlabel('Profit / Loss (₹)', color='#6b7280', fontsize=8)
        ax.set_title('Gainers & Losers', color='white', fontsize=10, pad=10)
        ax.tick_params(colors='#9ca3af', labelsize=8)
        ax.spines[:].set_color('#1f2937')
        ax.spines['right'].set_visible(False)
        ax.spines['top'].set_visible(False)

        plt.tight_layout()
        buf = io.BytesIO()
        plt.savefig(buf, format='png', dpi=120, bbox_inches='tight',
                    facecolor='#161b22', transparent=False)
        plt.close(fig)
        buf.seek(0)
        return buf
    except Exception as e:
        logger.warning(f"Bar chart failed: {e}")
        return None


def generate_pdf_report(
    holdings:         List[Dict],
    summary:          Dict,
    risk_metrics:     Optional[Dict] = None,
    advanced_metrics: Optional[Dict] = None,
    tax_data:         Optional[Dict] = None,
    portfolio_name:   str            = "My Portfolio",
) -> io.BytesIO:
    """
    Generate complete PDF portfolio report.
    Returns BytesIO buffer ready to stream.
    """
    buf    = io.BytesIO()
    s      = _styles()
    inr    = summary.get('inr', {})
    usd    = summary.get('usd', {})

    # ── Setup document ────────────────────────────────────────
    frame = Frame(
        20*mm, 14*mm,
        PAGE_W - 40*mm, PAGE_H - 28*mm,
        leftPadding=0, rightPadding=0,
        topPadding=0, bottomPadding=0,
    )
    doc = BaseDocTemplate(
        buf,
        pagesize=A4,
        leftMargin=20*mm, rightMargin=20*mm,
        topMargin=20*mm, bottomMargin=15*mm,
    )
    doc.addPageTemplates([
        PageTemplate(id='main', frames=[frame], onPage=_on_page)
    ])

    story = []

    # ── Cover ─────────────────────────────────────────────────
    story.append(Spacer(1, 8*mm))
    story.append(Paragraph("Portfolio Analysis", s["subtitle"]))
    story.append(Paragraph(portfolio_name, s["title"]))
    story.append(Paragraph(
        f"Generated {datetime.now().strftime('%d %B %Y at %H:%M IST')} · "
        f"{len(holdings)} holdings · Powered by PortfolioAI",
        s["small"]
    ))
    story.append(Spacer(1, 6*mm))
    story.append(HRFlowable(
        width="100%", thickness=1,
        color=colors.HexColor('#1e3a5f'), spaceAfter=8
    ))

    # ── Summary metrics ───────────────────────────────────────
    story.append(Paragraph("Portfolio Summary", s["section"]))

    total_inv  = inr.get('total_invested', 0)
    total_cur  = inr.get('total_current_value', 0)
    total_pnl  = inr.get('total_pnl', 0)
    total_pct  = inr.get('total_pnl_pct', 0)

    pnl_color  = '#22c55e' if total_pnl >= 0 else '#ef4444'
    pct_color  = '#22c55e' if total_pct >= 0 else '#ef4444'

    metrics = [
        ("Total Invested",     f"₹{total_inv:,.0f}",  '#9ca3af'),
        ("Current Value",      f"₹{total_cur:,.0f}",  '#ffffff'),
        ("Total P&L",          f"{'+'if total_pnl>=0 else''}₹{total_pnl:,.0f}", pnl_color),
        ("Return",             f"{'+'if total_pct>=0 else''}{total_pct:.2f}%",   pct_color),
        ("Holdings",           str(len(holdings)),     '#3b82f6'),
        ("Sectors",            str(len({h.get('sector','?') for h in holdings})), '#8b5cf6'),
    ]
    if usd.get('total_invested', 0) > 0:
        metrics.append(("USD Invested", f"${usd.get('total_invested',0):,.0f}", '#9ca3af'))
        metrics.append(("USD P&L",     f"{'+'if usd.get('total_pnl',0)>=0 else''}${usd.get('total_pnl',0):,.0f}",
                         '#22c55e' if usd.get('total_pnl',0)>=0 else '#ef4444'))

    story.append(_metric_table(metrics, cols=4))
    story.append(Spacer(1, 6*mm))

    # ── Risk metrics ──────────────────────────────────────────
    if risk_metrics:
        story.append(Paragraph("Risk Analytics", s["section"]))
        sharpe   = risk_metrics.get('sharpe_ratio', 0)
        vol      = risk_metrics.get('annualized_volatility_pct', 0)
        drawdown = risk_metrics.get('max_drawdown_pct', 0)
        beta     = risk_metrics.get('beta', 1.0)
        ann_ret  = risk_metrics.get('annualized_return_pct', 0)
        sortino  = risk_metrics.get('sortino_ratio', 0)

        risk_metrics_data = [
            ("Sharpe Ratio",     f"{sharpe:.3f}", '#22c55e' if sharpe>1 else '#f59e0b' if sharpe>0 else '#ef4444'),
            ("Sortino Ratio",    f"{sortino:.3f}", '#22c55e' if sortino>1 else '#f59e0b'),
            ("Annual Return",    f"{'+'if ann_ret>=0 else''}{ann_ret:.2f}%",
             '#22c55e' if ann_ret>=0 else '#ef4444'),
            ("Volatility",       f"{vol:.2f}%",
             '#22c55e' if vol<15 else '#f59e0b' if vol<25 else '#ef4444'),
            ("Max Drawdown",     f"{drawdown:.2f}%", '#ef4444'),
            ("Beta vs Nifty",    f"{beta:.3f}",
             '#22c55e' if abs(beta-1)<0.2 else '#f59e0b'),
        ]

        if advanced_metrics:
            var95 = advanced_metrics.get('var_95', 0)
            alpha = advanced_metrics.get('alpha', 0)
            if var95:
                risk_metrics_data.append(
                    ("VaR 95% (daily)", f"{var95:.3f}%", '#f59e0b')
                )
            if alpha:
                risk_metrics_data.append(
                    ("Alpha vs Nifty",
                     f"{'+'if alpha>=0 else''}{alpha:.2f}%",
                     '#22c55e' if alpha>=0 else '#ef4444')
                )

        story.append(_metric_table(risk_metrics_data, cols=4))
        story.append(Spacer(1, 3*mm))

        # Interpretation
        interp = risk_metrics.get('interpretation', {})
        if interp:
            interp_rows = []
            for k, v in interp.items():
                interp_rows.append([
                    Paragraph(k.capitalize(), ParagraphStyle(
                        "ik", fontSize=8, textColor=C_BLUE, fontName="Helvetica-Bold"
                    )),
                    Paragraph(str(v), s["body"]),
                ])
            t = Table(interp_rows, colWidths=[3.5*cm, PAGE_W - 40*mm - 3.5*cm])
            t.setStyle(TableStyle([
                ('BACKGROUND',  (0,0),(-1,-1), colors.HexColor('#0f1923')),
                ('TOPPADDING',  (0,0),(-1,-1), 5),
                ('BOTTOMPADDING',(0,0),(-1,-1),5),
                ('LEFTPADDING', (0,0),(-1,-1), 8),
                ('RIGHTPADDING',(0,0),(-1,-1), 8),
                ('LINEBELOW',   (0,0),(-1,-2), 0.3, colors.HexColor('#1f2937')),
                ('VALIGN',      (0,0),(-1,-1), 'TOP'),
            ]))
            story.append(t)
            story.append(Spacer(1, 4*mm))

    # ── Charts ────────────────────────────────────────────────
    story.append(Paragraph("Portfolio Analytics", s["section"]))

    sector_breakdown = (risk_metrics or {}).get('sector_breakdown', [])
    if not sector_breakdown:
        sector_map: Dict[str, float] = {}
        total_inv_v = sum(h.get('invested_value',0) for h in holdings)
        for h in holdings:
            sec = h.get('sector') or 'Unknown'
            sector_map[sec] = sector_map.get(sec, 0) + h.get('invested_value', 0)
        if total_inv_v > 0:
            sector_breakdown = [
                {"sector": k, "weight_pct": round(v/total_inv_v*100, 1)}
                for k, v in sorted(sector_map.items(), key=lambda x: -x[1])
            ]

    pie_buf  = _pie_chart(sector_breakdown)
    bar_buf  = _pnl_bar_chart(holdings)

    chart_row = []
    if pie_buf:
        chart_row.append(Image(pie_buf, width=8*cm, height=6.5*cm))
    if bar_buf:
        chart_row.append(Image(bar_buf, width=10*cm, height=6.5*cm))

    if chart_row:
        if len(chart_row) == 2:
            ct = Table([chart_row], colWidths=[8.5*cm, 10.5*cm])
            ct.setStyle(TableStyle([
                ('VALIGN',  (0,0),(-1,-1), 'TOP'),
                ('LEFTPADDING', (0,0),(-1,-1), 0),
                ('RIGHTPADDING',(0,0),(-1,-1), 0),
            ]))
            story.append(ct)
        else:
            story.append(chart_row[0])
        story.append(Spacer(1, 4*mm))

    # ── Holdings table ────────────────────────────────────────
    story.append(Paragraph(
        f"Holdings ({len(holdings)} stocks)", s["section"]
    ))
    story.append(_holdings_table(holdings))

    if len(holdings) > 30:
        story.append(Spacer(1, 2*mm))
        story.append(Paragraph(
            f"* Showing first 30 of {len(holdings)} holdings",
            s["small"]
        ))
    story.append(Spacer(1, 6*mm))

    # ── Tax summary ───────────────────────────────────────────
    if tax_data and tax_data.get('total_tax_with_cess', 0) > 0:
        story.append(PageBreak())
        story.append(Paragraph("Tax P&L Estimate", s["section"]))
        story.append(Paragraph(
            f"Financial Year: {tax_data.get('fy','FY2024-25')} · "
            "Budget 2024 rates · STCG 20% · LTCG 12.5% · Exemption ₹1.25L",
            s["small"]
        ))
        story.append(Spacer(1, 4*mm))

        tax_metrics = [
            ("STCG Gains",    f"₹{tax_data.get('total_stcg',0):,.0f}",     '#f97316'),
            ("LTCG Gains",    f"₹{tax_data.get('total_ltcg',0):,.0f}",     '#f59e0b'),
            ("LTCG Exempt",   f"₹{tax_data.get('ltcg_exempt',0):,.0f}",    '#22c55e'),
            ("LTCG Taxable",  f"₹{tax_data.get('ltcg_taxable',0):,.0f}",   '#f59e0b'),
            ("STCG Tax",      f"₹{tax_data.get('stcg_tax',0):,.0f}",       '#ef4444'),
            ("LTCG Tax",      f"₹{tax_data.get('ltcg_tax',0):,.0f}",       '#ef4444'),
            ("Total Tax",     f"₹{tax_data.get('total_tax',0):,.0f}",      '#ef4444'),
            ("With 4% Cess",  f"₹{tax_data.get('total_tax_with_cess',0):,.0f}", '#ef4444'),
        ]
        story.append(_metric_table(tax_metrics, cols=4))
        story.append(Spacer(1, 4*mm))

        if tax_data.get('summary_text'):
            story.append(Paragraph(tax_data['summary_text'], s["body"]))

        # Harvest suggestions
        harvests = tax_data.get('harvest_suggestions', [])
        if harvests:
            story.append(Spacer(1, 4*mm))
            story.append(Paragraph("Tax Harvesting Opportunities", s["section"]))
            for h in harvests[:5]:
                story.append(Paragraph(
                    f"<b>{h.get('symbol','')}</b> — {h.get('action','')} "
                    f"(Tax saving: ₹{h.get('tax_saved',0):,.0f})",
                    ParagraphStyle("hi", fontSize=9, textColor=C_GREEN,
                                   fontName="Helvetica", spaceAfter=3)
                ))
                story.append(Paragraph(h.get('explanation',''), s["small"]))

    # ── Disclaimer ────────────────────────────────────────────
    story.append(Spacer(1, 8*mm))
    story.append(HRFlowable(
        width="100%", thickness=0.5,
        color=colors.HexColor('#1f2937'), spaceAfter=6
    ))
    story.append(Paragraph(
        "DISCLAIMER: This report is generated by PortfolioAI for informational and educational "
        "purposes only. It does not constitute financial advice, investment recommendations, or "
        "tax advice. Past performance is not indicative of future results. Please consult a "
        "SEBI-registered investment advisor and Chartered Accountant before making investment "
        "or tax-related decisions. All data sourced from public market feeds.",
        s["small"]
    ))

    # ── Build PDF ─────────────────────────────────────────────
    doc.build(story)
    buf.seek(0)
    logger.info(f"PDF generated: {len(holdings)} holdings")
    return buf